# [Text2Text](https://github.com/artitw/text2text): Crosslingual NLP/G toolkit

## How Crosslingual Models Work (click to watch)
[![Crosslingual Models](http://img.youtube.com/vi/caZLVcJqsqo/0.jpg)](https://youtu.be/caZLVcJqsqo "Crosslingual Models")

In [ ]:
pip install -q -U text2text

     |████████████████████████████████| 69 kB 964 kB/s 
     |████████████████████████████████| 5.8 MB 32.1 MB/s 
     |████████████████████████████████| 17.0 MB 4.7 MB/s 
     |████████████████████████████████| 1.3 MB 51.3 MB/s 
     |████████████████████████████████| 7.6 MB 55.3 MB/s 
     |████████████████████████████████| 182 kB 45.4 MB/s 


In [ ]:
### Text Handler API quick start
import text2text as t2t
t2t.Transformer.PRETRAINED_TRANSLATOR = "facebook/m2m100_418M" #Remove this line for the larger model
h = t2t.Handler(["Hello, World!"], src_lang="en") #Initialize with some text
h.tokenize() #[['▁Hello', ',', '▁World', '!']]

Better speed can be achieved with apex installed.


Downloading:   0%|          | 0.00/272 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/908 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.71M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.14k [00:00<?, ?B/s]

[['▁Hello', ',', '▁World', '!']]

In [ ]:
h.vectorize() #array([[0.18745188, 0.05658336, 0.15895301, ..., 0.46946704, 0.6332584 , 0.43805206]], dtype=float32)

Downloading:   0%|          | 0.00/1.94G [00:00<?, ?B/s]

array([[0.0125036 , 0.00377429, 0.01060265, ..., 0.03131489, 0.04224026,
        0.0292194 ]], dtype=float32)

In [ ]:
h.tfidf() #[{'!': 0.5, ',': 0.5, '▁Hello': 0.5, '▁World': 0.5}]

[{'▁Hello': 0.5, ',': 0.5, '▁World': 0.5, '!': 0.5}]

In [ ]:
h.bm25() #[{'!': 0.5, ',': 0.5, '▁Hello': 0.5, '▁World': 0.5}]

[{'▁Hello': 0.3068528194400547,
  ',': 0.3068528194400547,
  '▁World': 0.3068528194400547,
  '!': 0.3068528194400547}]

In [ ]:
i = h.index() #Index object for similarity retrieval

Creating index with 128104 dimensions.


In [ ]:
h.search(queries=["Hello"]).toarray() #array([[0.5]])

array([[0.09415865]])

In [ ]:
h.translate(tgt_lang="zh") #['你好,世界!']

/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py:1387: UserWarning: Neither `max_length` nor `max_new_tokens` has been set, `max_length` will default to 200 (`self.config.max_length`). Controlling `max_length` via the config is deprecated and `max_length` will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


['你好,世界!']

In [ ]:
h.summarize() #["World ' s largest world"]

100%|██████████| 1/1 [00:03<00:00,  3.80s/it]


['Hello , World! Hello , World! Hello , World! Hello , World! Hello , World! Hello , World! Hello , World! Hello , World! Hello , World! Hello , World! Hello , World! Hello , World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World! World!']

In [ ]:
h.question() #[('What is the name of the world you are in?', 'The world')]

100%|██████████| 1/1 [00:01<00:00,  1.41s/it]


[('What is the name of the Hello , World!', 'world')]

In [ ]:
h.variate() #['Hello the world!', 'Welcome to the world.', 'Hello to the world!',...

['Hello the world!',
 'My brother and sister!',
 'Welcome to the world!',
 'Hello, the world',
 '“No to the world”',
 'It is clearly!',
 'Welcome to the light!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello, it’s a good thing!',
 'Congratulations to all!',
 'Hello to the world!',
 'Hello to the world!',
 'Good Morning, the World',
 'Welcome to the World!',
 'Hello the world!',
 'Hello the world!',
 'Good morning to the world!',
 'Hello, World!',
 'Hello the world!',
 'Fortunately the world!',
 'Hello to the world!',
 'We do it!',
 'Welcome to the world!',
 'Hello to the world!',
 'Go to the world!',
 'Member of the Board of Directors of the Board of Directors of the Board of Directors of the Board of Directors',
 'The world.',
 'Hello to the world!',
 'and it is!',
 'Hello, for the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Welcome to the world!',
 'Congratulations to the world!',
 'Hello

In [ ]:
t2t.Handler(["[CONTEXT] Hello EOS How are you?"]).respond() #['I am doing great. How are you?']

In [ ]:
t2t.Handler(["Hello, World! [SEP] Hello, what?"]).answer() #['World']

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/757 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/798k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/150 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/595M [00:00<?, ?B/s]

['World']

In [ ]:
t2t.Handler(["Hello, World! [SEP] Hello, what?"]).measure() #[2]

[2]

In [ ]:
t2t.Server(host='0.0.0.0', port=80)

Creating index with 128104 dimensions.
Serving at http://172.28.0.12/
 * Serving Flask app "text2text.server" (lazy loading)


 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


In [ ]:
import socket
import requests

address = socket.gethostbyname(socket.getfqdn(socket.gethostname()))
url = f"http://{address}"
transform = "translate"
payload = {
  "input_lines": ["hello", "world"], 
  "src_lang": "en",
  "tgt_lang": "ko",
}
r = requests.post(f"{url}/{transform}", json=payload)
print(r.json())
r = requests.post(f"{url}/index/add", json=payload)
print(r.json())
r = requests.post(f"{url}/index/size", json=payload)
print(r.json())
r = requests.post(f"{url}/index/search", json=payload)
print(r.json())
payload["ids"] = [0,1]
r = requests.post(f"{url}/index/remove", json=payload)
print(r.json())

INFO:werkzeug: * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
INFO:werkzeug:172.28.0.12 - - [15/Dec/2022 17:29:39] "POST /translate HTTP/1.1" 200 -


{'result': ['안녕하세요', '세계']}


INFO:werkzeug:172.28.0.12 - - [15/Dec/2022 17:29:40] "POST /index/add HTTP/1.1" 200 -
INFO:werkzeug:172.28.0.12 - - [15/Dec/2022 17:29:40] "POST /index/size HTTP/1.1" 200 -


{'result': 'index/add performed'}
{'result': 2}


INFO:werkzeug:172.28.0.12 - - [15/Dec/2022 17:29:41] "POST /index/search HTTP/1.1" 200 -
INFO:werkzeug:172.28.0.12 - - [15/Dec/2022 17:29:41] "POST /index/remove HTTP/1.1" 200 -


{'result': [[[0.0, 2.0, 3.4028234663852886e+38], [0.0, 2.0, 3.4028234663852886e+38]], [[1.0, 2.0, -1.0], [2.0, 1.0, -1.0]]]}
{'result': 'index/remove performed'}


In [ ]:
### Languages Available
t2t.Transformer.LANGUAGES

{'af': 'Afrikaans',
 'am': 'Amharic',
 'ar': 'Arabic',
 'ast': 'Asturian',
 'az': 'Azerbaijani',
 'ba': 'Bashkir',
 'be': 'Belarusian',
 'bg': 'Bulgarian',
 'bn': 'Bengali',
 'br': 'Breton',
 'bs': 'Bosnian',
 'ca': 'Catalan_Valencian',
 'ceb': 'Cebuano',
 'cs': 'Czech',
 'cy': 'Welsh',
 'da': 'Danish',
 'de': 'German',
 'el': 'Greeek',
 'en': 'English',
 'es': 'Spanish',
 'et': 'Estonian',
 'fa': 'Persian',
 'ff': 'Fulah',
 'fi': 'Finnish',
 'fr': 'French',
 'fy': 'Western_Frisian',
 'ga': 'Irish',
 'gd': 'Gaelic_Scottish_Gaelic',
 'gl': 'Galician',
 'gu': 'Gujarati',
 'ha': 'Hausa',
 'he': 'Hebrew',
 'hi': 'Hindi',
 'hr': 'Croatian',
 'ht': 'Haitian_Haitian_Creole',
 'hu': 'Hungarian',
 'hy': 'Armenian',
 'id': 'Indonesian',
 'ig': 'Igbo',
 'ilo': 'Iloko',
 'is': 'Icelandic',
 'it': 'Italian',
 'ja': 'Japanese',
 'jv': 'Javanese',
 'ka': 'Georgian',
 'kk': 'Kazakh',
 'km': 'Central_Khmer',
 'kn': 'Kannada',
 'ko': 'Korean',
 'lb': 'Luxembourgish_Letzeburgesch',
 'lg': 'Ganda',
 'ln':

In [ ]:
# Sample texts
article_en = 'The Secretary-General of the United Nations says there is no military solution in Syria.'
 
notre_dame_str = "As at most other universities, Notre Dame's students run a number of news media outlets. The nine student - run outlets include three newspapers, both a radio and television station, and several magazines and journals. Begun as a one - page journal in September 1876, the Scholastic magazine is issued twice monthly and claims to be the oldest continuous collegiate publication in the United States. The other magazine, The Juggler, is released twice a year and focuses on student literature and artwork. The Dome yearbook is published annually. The newspapers have varying publication interests, with The Observer published daily and mainly reporting university and other news, and staffed by students from both Notre Dame and Saint Mary's College. Unlike Scholastic and The Dome, The Observer is an independent publication and does not have a faculty advisor or any editorial oversight from the University. In 1987, when some students believed that The Observer began to show a conservative bias, a liberal newspaper, Common Sense was published. Likewise, in 2003, when other students believed that the paper showed a liberal bias, the conservative paper Irish Rover went into production. Neither paper is published as often as The Observer; however, all three are distributed to all students. Finally, in Spring 2008 an undergraduate journal for political science research, Beyond Politics, made its debut."
 
bacteria_str = "Bacteria are a type of biological cell. They constitute a large domain of prokaryotic microorganisms. Typically a few micrometres in length, bacteria have a number of shapes, ranging from spheres to rods and spirals. Bacteria were among the first life forms to appear on Earth, and are present in most of its habitats."
 
bio_str = "Biology is the science that studies life. What exactly is life? This may sound like a silly question with an obvious answer, but it is not easy to define life. For example, a branch of biology called virology studies viruses, which exhibit some of the characteristics of living entities but lack others. It turns out that although viruses can attack living organisms, cause diseases, and even reproduce, they do not meet the criteria that biologists use to define life."
 

In [ ]:
### Tokenization
t2t.Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).tokenize()

[['▁Let', "'", 's', '▁go', '▁hik', 'ing', '▁tom', 'orrow'],
 ['▁안녕', '하세요', '.'],
 ['▁', '돼', '지', '꿈', '을', '▁꾸', '세요', '~~']]

In [ ]:
# Embeddings
t2t.Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).vectorize()

array([[-0.00352955,  0.02600589,  0.0040743 , ..., -0.04830331,
        -0.02540749, -0.00924972],
       [ 0.00218413,  0.00243838,  0.0076672 , ...,  0.01991539,
         0.0227027 ,  0.0075313 ],
       [-0.03563677, -0.04856303,  0.00518897, ..., -0.00311067,
         0.00071953, -0.00216326]], dtype=float32)

In [ ]:
### TF-IDF
t2t.Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).tfidf()

[{'▁Let': 0.3535533905932738,
  "'": 0.3535533905932738,
  's': 0.3535533905932738,
  '▁go': 0.3535533905932738,
  '▁hik': 0.3535533905932738,
  'ing': 0.3535533905932738,
  '▁tom': 0.3535533905932738,
  'orrow': 0.3535533905932738},
 {'▁안녕': 0.5773502691896258,
  '하세요': 0.5773502691896258,
  '.': 0.5773502691896258},
 {'▁': 0.3535533905932738,
  '돼': 0.3535533905932738,
  '지': 0.3535533905932738,
  '꿈': 0.3535533905932738,
  '을': 0.3535533905932738,
  '▁꾸': 0.3535533905932738,
  '세요': 0.3535533905932738,
  '~~': 0.3535533905932738}]

In [ ]:
### BM25
t2t.Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).bm25()

[{'▁Let': 1.2792257271403649,
  "'": 1.2792257271403649,
  's': 1.2792257271403649,
  '▁go': 1.2792257271403649,
  '▁hik': 1.2792257271403649,
  'ing': 1.2792257271403649,
  '▁tom': 1.2792257271403649,
  'orrow': 1.2792257271403649},
 {'▁안녕': 1.751071282233123, '하세요': 1.751071282233123, '.': 1.751071282233123},
 {'▁': 1.2792257271403649,
  '돼': 1.2792257271403649,
  '지': 1.2792257271403649,
  '꿈': 1.2792257271403649,
  '을': 1.2792257271403649,
  '▁꾸': 1.2792257271403649,
  '세요': 1.2792257271403649,
  '~~': 1.2792257271403649}]

In [ ]:
### Index
index = t2t.Handler([
         "Let's go hiking tomorrow, let's go!", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~",
         ]).index(ids=[100, 101, 102])

index.search(["돼지", "안녕", "let's go"], k=1) # Matching L2 distances and corresponding ids

Creating index with 128104 dimensions.


(array([[0.7752551],
        [0.8452994],
        [0.4347524]], dtype=float32), array([[102],
        [101],
        [100]]))

In [ ]:
# Add documents incrementing on ids if none specified
index.add(["Hello, World! 你好,世界!"])

# Remove by ids
index.remove([101])

# Retrieve k results per query sorted by distance
index.search(["你好, World"], k=3)

(array([[0.61324954, 1.7763932 , 2.        ]], dtype=float32),
 array([[103, 100, 102]]))

In [ ]:
### Search
t2t.Handler([
         "Let's go hiking tomorrow, let's go!", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~",
         ]).search(queries=["go", "안녕"]).toarray()

array([[1.60166964, 0.        , 0.        ],
       [0.        , 1.84929619, 0.        ]])

In [ ]:
#### Multiple queries on a single index
bm25_index = t2t.Handler([
                       article_en, 
                       notre_dame_str, 
                       bacteria_str, 
                       bio_str
                       ]).bm25(output="matrix")

search_results_bm25 = t2t.Handler().search(
    queries=["wonderful life", "university students"], 
    vector_class=t2t.Bm25er,
    index=bm25_index)

search_results_bm25_2 = t2t.Handler().search(
    queries=["Earth creatures are cool", "United Nations"], 
    vector_class=t2t.Bm25er,
    index=bm25_index)

In [ ]:
#### Using TF-DF embeddings index
tfidf_index = t2t.Handler([
                       article_en, 
                       notre_dame_str, 
                       bacteria_str, 
                       bio_str
                       ]).tfidf(output="matrix")

search_results_tf = t2t.Handler().search(
    queries=["wonderful life", "university students"], 
    vector_class=t2t.Tfidfer,
    index=tfidf_index)

In [ ]:
#### Using neural embeddings index
embedding_index = t2t.Handler([
                       article_en, 
                       notre_dame_str, 
                       bacteria_str, 
                       bio_str
                       ]).vectorize()

search_results_em = t2t.Handler().search(
    queries=["wonderful life", "university students"],
    vector_class=t2t.Vectorizer,
    index=embedding_index)

In [ ]:
#### Blending neural embeddings and tf-idf
import numpy as np

np.mean( 
    np.array([
              search_results_bm25,
              search_results_tf,
              search_results_em,
              ]), axis=0)

# averaged scores matrix
#matrix([[ 0.00486117, -0.01890325,  0.53769584,  0.82506883],
#        [ 0.0435048 ,  1.68977281,  0.01238902,  0.01266839]])

<ipython-input-28-f2a1ae447004>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([


matrix([[ 0.19740325, -0.08608283,  0.75373231,  1.03017544],
        [ 0.01763532,  1.68977281,  0.02004045,  0.02080889]])

In [ ]:
### Levenshtein Sub-word Edit Distance
t2t.Handler([
         "Hello, World! [SEP] Hello, what?", 
         "안녕하세요. [SEP] 돼지꿈을 꾸세요~~"
        ]).measure(metric="levenshtein_distance")

[2, 8]

In [ ]:
### Translation
# Default translator model
t2t.Handler([article_en, notre_dame_str, bacteria_str, bio_str], src_lang='en').translate(tgt_lang='zh')

['联合国秘书长说,叙利亚没有军事解决方案。',
 '正如大多数其他大学一样,Notre Dame的学生运行了一些新闻媒体出版物。 九个学生 - 运行出版物包括三个报纸,无论是广播和电视台,以及几个杂志和杂志。 作为一个 - 页面杂志在1876年9月发行,Scholastic杂志每月两次,声称是美国最古老的持续的大学出版物。 另一个杂志,The Juggler,每年发行两次,并专注于学生文学和艺术作品。',
 '细菌是生物细胞的一种类型,它们构成一个大域的益生菌微生物,通常有几米长的细菌有几种形状,从分支到根和螺旋,细菌是地球上出现的第一种生命形式之一,并且在其大多数栖息地中存在。',
 '生物学是研究生命的科学,究竟什么是生命?这可能听起来像一个愚蠢的问题,有一个显而易见的答案,但不容易定义生命。 例如,生物学的一个分支称为病毒学研究病毒,它展示了一些生物的特征,但缺乏其他。']

In [ ]:
# Smaller model to save time and memory for development
t2t.Transformer.PRETRAINED_TRANSLATOR = "facebook/m2m100_418M"
t2t.Handler(["I would like to go hiking tomorrow."], 
        src_lang="en"
        ).translate(tgt_lang='zh')


['我想明天去散步。']

In [ ]:
import text2text as t2t
# Smaller model to save time and memory for development
# Note language code differences
# Might have to restart runtime if running in Google Colab
t2t.Transformer.PRETRAINED_TRANSLATOR = "facebook/mbart-large-50-many-to-many-mmt"
t2t.Transformer.LANGUAGES = {
  'af_ZA': 'Afrikaans',
  'ar_AR': 'Arabic',
  'az_AZ': 'Azerbaijani',
  'bn_IN': 'Bengali',
  'cs_CZ': 'Czech',
  'de_DE': 'German',
  'en_XX': 'English',
  'es_XX': 'Spanish',
  'et_EE': 'Estonian',
  'fa_IR': 'Persian',
  'fi_FI': 'Finnish',
  'fr_XX': 'French',
  'gl_ES': 'Galician',
  'gu_IN': 'Gujarati',
  'he_IL': 'Hebrew',
  'hi_IN': 'Hindi',
  'hr_HR': 'Croatian',
  'id_ID': 'Indonesian',
  'it_IT': 'Italian',
  'ja_XX': 'Japanese',
  'ka_GE': 'Georgian',
  'kk_KZ': 'Kazakh',
  'km_KH': 'Khmer',
  'ko_KR': 'Korean',
  'lt_LT': 'Lithuanian',
  'lv_LV': 'Latvian',
  'mk_MK': 'Macedonian',
  'ml_IN': 'Malayalam',
  'mn_MN': 'Mongolian',
  'mr_IN': 'Marathi',
  'my_MM': 'Burmese',
  'ne_NP': 'Nepali',
  'nl_XX': 'Dutch',
  'pl_PL': 'Polish',
  'ps_AF': 'Pashto',
  'pt_XX': 'Portuguese',
  'ro_RO': 'Romanian',
  'ru_RU': 'Russian',
  'si_LK': 'Sinhala',
  'sl_SI': 'Slovene',
  'sv_SE': 'Swedish',
  'sw_KE': 'Swahili',
  'ta_IN': 'Tamil',
  'te_IN': 'Telugu',
  'th_TH': 'Thai',
  'tl_XX': 'Tagalog',
  'tr_TR': 'Turkish',
  'uk_UA': 'Ukrainian',
  'ur_PK': 'Urdu',
  'vi_VN': 'Vietnamese',
  'xh_ZA': 'Xhosa',
  'zh_CN': 'Chinese'
}
t2t.Handler(["I would like to go hiking tomorrow."], 
        src_lang="en_XX"
        ).translate(tgt_lang='zh_CN')


Better speed can be achieved with apex installed.


Downloading:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.44G [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/529 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/649 [00:00<?, ?B/s]

In [ ]:
### Question Answering. Question must follow context with ` [SEP] ` in between.
t2t.Handler([
         "Hello, this is Text2Text! [SEP] What is this?", 
         "It works very well. It's awesome! [SEP] How is it?"
         ]).answer()

In [ ]:
t2t.Handler(["很喜欢陈慧琳唱歌。[SEP] 喜欢做什么?"], 
        src_lang="zh",
        ).answer()

In [ ]:
### Question Generation
t2t.Handler([
            bio_str,
            bio_str,
            bio_str,
            bio_str,
            bio_str,
            "I will go to school today to take my math exam.",
            "I will go to school today to take my math exam.",
            "Tomorrow is my cousin's birthday. He will turn 24 years old.",
            notre_dame_str,
            bacteria_str,
            bacteria_str,
            bacteria_str,
            "I will go to school today to take my math exam. [SEP] school",
            "I will go to school today to take my math exam. [SEP] exam",
            "I will go to school today to take my math exam. [SEP] math",
          ], src_lang='en').question()

In [ ]:
t2t.Handler(["很喜欢陈慧琳唱歌。"], src_lang='zh').question()

In [ ]:
### Summarization
t2t.Handler([notre_dame_str, bacteria_str, bio_str], src_lang='en').summarize()

In [ ]:
### Variation
# Useful for augmenting training data
t2t.Handler([bacteria_str], src_lang='en').variate()

In [ ]:
### Dialog Responder
# Respond to given instructions, knowledge base, and dialog context.

instruction = ''
knowledge = 'Domestic cats are valued by humans for companionship and their ability to kill rodents. About 60 cat breeds are recognized by various cat registries.'
dialog = [
    'Tell me about cats',
    'There are many different breeds of cats in the world.',
    'How many kinds are there?'
]

if knowledge != '':
    knowledge = '[KNOWLEDGE] ' + knowledge
dialog = ' EOS '.join(dialog)
input_state = f"{instruction} [CONTEXT] {dialog} {knowledge}"

t2t.Handler([input_state]).respond()
# ['About 60 different kinds of cats are recognized by various cat registries.']

In [ ]:
### Training / Fine-tuning
# Finetune cross-lingual model on your data
result = t2t.Handler(["Hello, World! [TGT] 你好,世界!"], 
            src_lang="en",
            tgt_lang="zh",
            num_epochs=10, 
            save_directory="model_dir"
            ).fit()

# load and use model from saved directory
t2t.Transformer.PRETRAINED_TRANSLATOR = "model_dir"
t2t.Handler("Hello, World!").translate(tgt_lang="zh")