# [Text2Text](https://github.com/artitw/text2text): Multilingual tokenization, embedding, translation, summarization, question generation, question answering, data augmentation, distance measurement

## How Cross-Lingual NLP Models Work (click to watch)
[![Cross-Lingual Models](http://img.youtube.com/vi/caZLVcJqsqo/0.jpg)](https://youtu.be/caZLVcJqsqo "Cross-Lingual Models")


In [ ]:
pip install -U text2text

     |████████████████████████████████| 71kB 5.7MB/s 
     |████████████████████████████████| 2.3MB 14.0MB/s 
     |████████████████████████████████| 1.2MB 42.6MB/s 
     |████████████████████████████████| 901kB 42.3MB/s 
     |████████████████████████████████| 3.3MB 38.4MB/s 


In [ ]:
%%bash
export CUDA_HOME=/usr/local/cuda-10.1
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" pytorch-extension

Created temporary directory: /tmp/pip-ephem-wheel-cache-u8e9id1e
Created temporary directory: /tmp/pip-req-tracker-o7ov7_q6
Created requirements tracker '/tmp/pip-req-tracker-o7ov7_q6'
Created temporary directory: /tmp/pip-install-9giq3plo
1 location(s) to search for versions of pytorch-extension:
* https://pypi.org/simple/pytorch-extension/
Getting page https://pypi.org/simple/pytorch-extension/
Found index url https://pypi.org/simple
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/pytorch-extension/ HTTP/1.1" 200 448
Analyzing links from page https://pypi.org/simple/pytorch-extension/
  Found link https://files.pythonhosted.org/packages/fc/82/55f5774e1822dcd92a171389fd9ea9e532c4e44dcc0af00d463ed62537d3/pytorch-extension-0.1.tar.gz#sha256=a0c231ff62097ac9fab0b0fda2ceb4ca03cad7b93d9b399d48c33995faaf946a (from https://pypi.org/simple/pytorch-extension/), version: 0.1
  Skipping link: No binaries permitted for pytorch-extension: https://files.pythonhoste

/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py:283: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
    Running command python setup.py egg_info
    torch.__version__  =  1.8.1+cu101
    running egg_info
    creating /tmp/pip-install-9giq3plo/pytorch-extension/pip-egg-info/pytorch_extension.egg-info
    writing /tmp/pip-install-9giq3plo/pytorch-extension/pip-egg-info/pytorch_extension.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-9giq3plo/pytorch-extension/pip-egg-info/pytorch_extension.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-9giq3plo/pytorch-extension/pip-egg-info/pytorch_extension.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-9giq3plo/pytorch-extension/pip-egg-info/pytorch_extension.egg-info/SOURCES.txt'
    reading manifest file '/tmp/pip-install-9giq3plo/pytorch-e

In [ ]:
### Text Handler API quick start
from text2text import Handler, Transformer
Transformer.pretrained_translator = "facebook/m2m100_418M" #Remove this line for the larger model
h = Handler(["Hello, World!"], src_lang="en") #Initialize with some text
h.tokenize() #[['▁Hello', ',', '▁World', '!']]

Better speed can be achieved with apex installed from https://www.github.com/artitw/apex.


[['▁Hello', ',', '▁World', '!']]

In [ ]:
h.vectorize() #array([[0.18745188, 0.05658336, 0.15895301, ..., 0.46946704, 0.6332584 , 0.43805206]], dtype=float32)

[array([0.0125036 , 0.00377428, 0.01060264, ..., 0.0313149 , 0.04224026,
        0.02921942])]

In [ ]:
h.tfidf() #[{'!': 0.5, ',': 0.5, '▁Hello': 0.5, '▁World': 0.5}]

[{'!': 0.5, ',': 0.5, '▁Hello': 0.5, '▁World': 0.5}]

In [ ]:
h.search(queries=["Hello"]) #array([[0.5]])

array([[0.5]])

In [ ]:
h.translate(tgt_lang="zh") #['你好,世界!']

['你好,世界!']

In [ ]:
h.summarize() #["World ' s largest world"]

100%|██████████| 213450/213450 [00:00<00:00, 784787.15B/s]


***** Recover model: cnndm_model.bin *****


100%|██████████| 1/1 [00:02<00:00,  2.85s/it]


['Hello , World!  Have you ever been a member of the World War II.']

In [ ]:
h.question() #[('What is the name of the world you are in?', 'The world')]

***** Recover model: qg_model.bin *****


100%|██████████| 1/1 [00:01<00:00,  1.03s/it]


[('What is the name of the Hello , World!', 'world')]

In [ ]:
h.variate() #['Hello the world!', 'Welcome to the world.', 'Hello to the world!',...

['Hello the world!',
 'My brother and sister!',
 'Welcome to the world!',
 'Hello, the world',
 '“No to the world”',
 'It is clearly!',
 'Welcome to the light!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello, it’s a good thing!',
 'Congratulations to all!',
 'Hello to the world!',
 'Hello to the world!',
 'Good Morning, the World',
 'Welcome to the World!',
 'Hello the world!',
 'Hello the world!',
 'Good morning to the world!',
 'Hello, World!',
 'Hello the world!',
 'Fortunately the world!',
 'Hello to the world!',
 'We do it!',
 'Welcome to the world!',
 'Hello to the world!',
 'Go to the world!',
 'Member of the Board of Directors of the Board of Directors of the Board of Directors of the Board of Directors',
 'The world.',
 'Hello to the world!',
 'and it is!',
 'Hello, for the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Welcome to the world!',
 'Congratulations to the world!',
 'Hello

In [ ]:
Handler(["Hello, World! [SEP] Hello, what?"]).answer() #['World']

['World']

In [ ]:
Handler(["Hello, World! [SEP] Hello, what?"]).measure() #[2]

[2]

In [ ]:
### Languages Available
from text2text import Transformer
Transformer.LANGUAGES

{'af': 'Afrikaans',
 'am': 'Amharic',
 'ar': 'Arabic',
 'ast': 'Asturian',
 'az': 'Azerbaijani',
 'ba': 'Bashkir',
 'be': 'Belarusian',
 'bg': 'Bulgarian',
 'bn': 'Bengali',
 'br': 'Breton',
 'bs': 'Bosnian',
 'ca': 'Catalan_Valencian',
 'ceb': 'Cebuano',
 'cs': 'Czech',
 'cy': 'Welsh',
 'da': 'Danish',
 'de': 'German',
 'el': 'Greeek',
 'en': 'English',
 'es': 'Spanish',
 'et': 'Estonian',
 'fa': 'Persian',
 'ff': 'Fulah',
 'fi': 'Finnish',
 'fr': 'French',
 'fy': 'Western_Frisian',
 'ga': 'Irish',
 'gd': 'Gaelic_Scottish_Gaelic',
 'gl': 'Galician',
 'gu': 'Gujarati',
 'ha': 'Hausa',
 'he': 'Hebrew',
 'hi': 'Hindi',
 'hr': 'Croatian',
 'ht': 'Haitian_Haitian_Creole',
 'hu': 'Hungarian',
 'hy': 'Armenian',
 'id': 'Indonesian',
 'ig': 'Igbo',
 'ilo': 'Iloko',
 'is': 'Icelandic',
 'it': 'Italian',
 'ja': 'Japanese',
 'jv': 'Javanese',
 'ka': 'Georgian',
 'kk': 'Kazakh',
 'km': 'Central_Khmer',
 'kn': 'Kannada',
 'ko': 'Korean',
 'lb': 'Luxembourgish_Letzeburgesch',
 'lg': 'Ganda',
 'ln':

In [ ]:
# Sample texts
article_en = 'The Secretary-General of the United Nations says there is no military solution in Syria.'
 
notre_dame_str = "As at most other universities, Notre Dame's students run a number of news media outlets. The nine student - run outlets include three newspapers, both a radio and television station, and several magazines and journals. Begun as a one - page journal in September 1876, the Scholastic magazine is issued twice monthly and claims to be the oldest continuous collegiate publication in the United States. The other magazine, The Juggler, is released twice a year and focuses on student literature and artwork. The Dome yearbook is published annually. The newspapers have varying publication interests, with The Observer published daily and mainly reporting university and other news, and staffed by students from both Notre Dame and Saint Mary's College. Unlike Scholastic and The Dome, The Observer is an independent publication and does not have a faculty advisor or any editorial oversight from the University. In 1987, when some students believed that The Observer began to show a conservative bias, a liberal newspaper, Common Sense was published. Likewise, in 2003, when other students believed that the paper showed a liberal bias, the conservative paper Irish Rover went into production. Neither paper is published as often as The Observer; however, all three are distributed to all students. Finally, in Spring 2008 an undergraduate journal for political science research, Beyond Politics, made its debut."
 
bacteria_str = "Bacteria are a type of biological cell. They constitute a large domain of prokaryotic microorganisms. Typically a few micrometres in length, bacteria have a number of shapes, ranging from spheres to rods and spirals. Bacteria were among the first life forms to appear on Earth, and are present in most of its habitats."
 
bio_str = "Biology is the science that studies life. What exactly is life? This may sound like a silly question with an obvious answer, but it is not easy to define life. For example, a branch of biology called virology studies viruses, which exhibit some of the characteristics of living entities but lack others. It turns out that although viruses can attack living organisms, cause diseases, and even reproduce, they do not meet the criteria that biologists use to define life."
 

In [ ]:
from text2text import Handler
### Tokenization
Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).tokenize()

Better speed can be achieved with apex installed from https://www.github.com/artitw/apex.


[['▁Let', "'", 's', '▁go', '▁hik', 'ing', '▁tom', 'orrow'],
 ['▁안녕', '하세요', '.'],
 ['▁', '돼', '지', '꿈', '을', '▁꾸', '세요', '~~']]

In [ ]:
# Embeddings
Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).vectorize()

[array([-0.00352954,  0.0260059 ,  0.00407429, ..., -0.04830331,
        -0.02540749, -0.00924972]),
 array([0.00043362, 0.00249816, 0.01755436, ..., 0.04451273, 0.05118701,
        0.01895813]),
 array([-0.03563676, -0.04856304,  0.00518898, ..., -0.00311068,
         0.00071953, -0.00216325])]

In [ ]:
### TF-IDF
Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).tfidf()

[{"'": 0.3535533905932738,
  'ing': 0.3535533905932738,
  'orrow': 0.3535533905932738,
  's': 0.3535533905932738,
  '▁Let': 0.3535533905932738,
  '▁go': 0.3535533905932738,
  '▁hik': 0.3535533905932738,
  '▁tom': 0.3535533905932738},
 {'.': 0.5773502691896258,
  '▁안녕': 0.5773502691896258,
  '하세요': 0.5773502691896258},
 {'~~': 0.3535533905932738,
  '▁': 0.3535533905932738,
  '▁꾸': 0.3535533905932738,
  '꿈': 0.3535533905932738,
  '돼': 0.3535533905932738,
  '세요': 0.3535533905932738,
  '을': 0.3535533905932738,
  '지': 0.3535533905932738}]

In [ ]:
### Search
Handler([
         "Let's go hiking tomorrow, let's go!", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~",
         ]).search(queries=["go", "안녕"])

array([[0.4472136 , 0.        , 0.        ],
       [0.        , 0.57735027, 0.        ]])

In [ ]:
#### Multiple queries on a single index
tfidf_index = Handler([
                       article_en, 
                       notre_dame_str, 
                       bacteria_str, 
                       bio_str
                       ]).tfidf(output="ids")
search_results_tf1 = Handler().search(
    queries=["wonderful life", "university students"], 
    index=tfidf_index)
search_results_tf2 = Handler().search(
    queries=["Earth creatures are cool", "United Nations"], 
    index=tfidf_index)

In [ ]:
#### Using neural embeddings index
embedding_index = Handler([
                       article_en, 
                       notre_dame_str, 
                       bacteria_str, 
                       bio_str
                       ]).vectorize()
search_results_em1 = Handler().search(
    queries=["wonderful life", "university students"],
    class_name="Vectorizer",
    index=embedding_index)
search_results_em2 = Handler().search(
    queries=["Earth creatures are cool", "United Nations"],
    class_name="Vectorizer", 
    index=embedding_index)

In [ ]:
#### Blending neural embeddings and tf-idf
import numpy as np
np.mean( 
    np.array([
              search_results_tf1, 
              search_results_em1,
              ]), axis=0)

array([[ 0.00729176, -0.02835486,  0.0024925 ,  0.08656652],
       [ 0.06525719,  0.13328168,  0.0185835 ,  0.01900256]])

In [ ]:
### Levenshtein Sub-word Edit Distance
Handler([
         "Hello, World! [SEP] Hello, what?", 
         "안녕하세요. [SEP] 돼지꿈을 꾸세요~~"
        ]).measure(metric="levenshtein_distance")


[2, 8]

In [ ]:
### Translation
# Default translator model
Handler([article_en, notre_dame_str, bacteria_str, bio_str], src_lang='en').translate(tgt_lang='zh')

In [ ]:
# Smaller model to save time and memory for development
Handler(["I would like to go hiking tomorrow."], 
        src_lang="en", 
        pretrained_translator="facebook/m2m100_418M"
        ).translate(tgt_lang='zh')

In [ ]:
# Smaller model to save time and memory for development
# Note language code difference
Handler(["I would like to go hiking tomorrow."], 
        src_lang="en_XX", 
        pretrained_translator="facebook/mbart-large-50-many-to-many-mmt"
        ).translate(tgt_lang='zh_CN')

In [ ]:
### Question Answering. Question must follow context with ` [SEP] ` in between.
Handler([
         "Hello, this is Text2Text! [SEP] What is this?", 
         "It works very well. It's awesome! [SEP] How is it?"
         ]).answer()

In [ ]:
Handler(["很喜欢陈慧琳唱歌。[SEP] 喜欢做什么?"], 
        src_lang="zh",
        pretrained_translator="facebook/m2m100_418M"
        ).answer()

In [ ]:
### Question Generation
Handler(["很喜欢陈慧琳唱歌。"], src_lang='zh').question()
Handler([
            bio_str,
            bio_str,
            bio_str,
            bio_str,
            bio_str,
            "I will go to school today to take my math exam.",
            "I will go to school today to take my math exam.",
            "Tomorrow is my cousin's birthday. He will turn 24 years old.",
            notre_dame_str,
            bacteria_str,
            bacteria_str,
            bacteria_str,
            "I will go to school today to take my math exam. [SEP] school",
            "I will go to school today to take my math exam. [SEP] exam",
            "I will go to school today to take my math exam. [SEP] math",
          ], src_lang='en').question()

In [ ]:
### Summarization
Handler([notre_dame_str, bacteria_str, bio_str], src_lang='en').summarize()

In [ ]:
### Variation
# Useful for augmenting training data
Handler([bacteria_str], src_lang='en').variate()