# [Text2Text](https://github.com/artitw/text2text): Crosslingual NLP/G toolkit

## How Crosslingual Models Work (click to watch)
[![Crosslingual Models](http://img.youtube.com/vi/caZLVcJqsqo/0.jpg)](https://youtu.be/caZLVcJqsqo "Crosslingual Models")

In [ ]:
pip install -q -U text2text

     |████████████████████████████████| 67 kB 3.6 MB/s 
     |████████████████████████████████| 4.7 MB 15.9 MB/s 
     |████████████████████████████████| 4.7 MB 56.5 MB/s 
     |████████████████████████████████| 1.3 MB 48.8 MB/s 
     |████████████████████████████████| 6.6 MB 46.9 MB/s 
     |████████████████████████████████| 120 kB 63.5 MB/s 


In [ ]:
%%bash
sudo apt-get -qq install libopenblas-dev
sudo apt-get -qq install libomp-dev

Selecting previously unselected package libomp5:amd64.
(Reading database ... 155685 files and directories currently installed.)
Preparing to unpack .../libomp5_5.0.1-1_amd64.deb ...
Unpacking libomp5:amd64 (5.0.1-1) ...
Selecting previously unselected package libomp-dev.
Preparing to unpack .../libomp-dev_5.0.1-1_amd64.deb ...
Unpacking libomp-dev (5.0.1-1) ...
Setting up libomp5:amd64 (5.0.1-1) ...
Setting up libomp-dev (5.0.1-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.5) ...


debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 2.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 


In [ ]:
### Text Handler API quick start
import text2text as t2t
t2t.Transformer.PRETRAINED_TRANSLATOR = "facebook/m2m100_418M" #Remove this line for the larger model
h = t2t.Handler(["Hello, World!"], src_lang="en") #Initialize with some text
h.tokenize() #[['▁Hello', ',', '▁World', '!']]

Better speed can be achieved with apex installed.


[['▁Hello', ',', '▁World', '!']]

In [ ]:
h.vectorize() #array([[0.18745188, 0.05658336, 0.15895301, ..., 0.46946704, 0.6332584 , 0.43805206]], dtype=float32)

Downloading:   0%|          | 0.00/1.80G [00:00<?, ?B/s]

array([[0.0125036 , 0.00377429, 0.01060266, ..., 0.03131488, 0.04224026,
        0.02921941]], dtype=float32)

In [ ]:
h.tfidf() #[{'!': 0.5, ',': 0.5, '▁Hello': 0.5, '▁World': 0.5}]

[{'!': 0.5, ',': 0.5, '▁Hello': 0.5, '▁World': 0.5}]

In [ ]:
h.bm25() #[{'!': 0.5, ',': 0.5, '▁Hello': 0.5, '▁World': 0.5}]

[{'!': 0.3068528194400547,
  ',': 0.3068528194400547,
  '▁Hello': 0.3068528194400547,
  '▁World': 0.3068528194400547}]

In [ ]:
i = h.index() #Index object for similarity retrieval

In [ ]:
h.search(queries=["Hello"]).toarray() #array([[0.5]])

array([[0.09415865]])

In [ ]:
h.translate(tgt_lang="zh") #['你好,世界!']

['你好,世界!']

In [ ]:
h.summarize() #["World ' s largest world"]

In [ ]:
h.question() #[('What is the name of the world you are in?', 'The world')]

100%|██████████| 1/1 [00:02<00:00,  2.09s/it]


[('What is the name of the person who is in charge of the world?', 'hello')]

In [ ]:
h.variate() #['Hello the world!', 'Welcome to the world.', 'Hello to the world!',...

['Hello the world!',
 'My brother and sister!',
 'Welcome to the world!',
 'Hello, the world',
 '“No to the world”',
 'It is clearly!',
 'Welcome to the light!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello, it’s a good thing!',
 'Congratulations to all!',
 'Hello to the world!',
 'Hello to the world!',
 'Good Morning, the World',
 'Welcome to the World!',
 'Hello the world!',
 'Hello the world!',
 'Good morning to the world!',
 'Hello, World!',
 'Hello the world!',
 'Fortunately the world!',
 'Hello to the world!',
 'We do it!',
 'Welcome to the world!',
 'Hello to the world!',
 'Go to the world!',
 'Member of the Board of Directors of the Board of Directors of the Board of Directors of the Board of Directors',
 'The world.',
 'Hello to the world!',
 'and it is!',
 'Hello, for the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Hello to the world!',
 'Welcome to the world!',
 'Congratulations to the world!',
 'Hello

In [ ]:
t2t.Handler(["Hello, World! [SEP] Hello, what?"]).answer() #['World']

Downloading:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/757 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/780k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/446k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/150 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/567M [00:00<?, ?B/s]

['World']

In [ ]:
t2t.Handler(["Hello, World! [SEP] Hello, what?"]).measure() #[2]

[2]

In [ ]:
t2t.Server(host='0.0.0.0', port=80)

In [ ]:
import socket
import requests

address = socket.gethostbyname(socket.getfqdn(socket.gethostname()))
url = f"http://{address}"
transform = "translate"
payload = {
  "input_lines": ["hello", "world"], 
  "src_lang": "en",
  "tgt_lang": "ko",
}
r = requests.post(f"{url}/{transform}", json=payload)
print(r.json())
r = requests.post(f"{url}/index/add", json=payload)
print(r.json())
r = requests.post(f"{url}/index/size", json=payload)
print(r.json())
r = requests.post(f"{url}/index/search", json=payload)
print(r.json())
payload["ids"] = [0,1]
r = requests.post(f"{url}/index/remove", json=payload)
print(r.json())

In [ ]:
### Languages Available
t2t.Transformer.LANGUAGES

{'af': 'Afrikaans',
 'am': 'Amharic',
 'ar': 'Arabic',
 'ast': 'Asturian',
 'az': 'Azerbaijani',
 'ba': 'Bashkir',
 'be': 'Belarusian',
 'bg': 'Bulgarian',
 'bn': 'Bengali',
 'br': 'Breton',
 'bs': 'Bosnian',
 'ca': 'Catalan_Valencian',
 'ceb': 'Cebuano',
 'cs': 'Czech',
 'cy': 'Welsh',
 'da': 'Danish',
 'de': 'German',
 'el': 'Greeek',
 'en': 'English',
 'es': 'Spanish',
 'et': 'Estonian',
 'fa': 'Persian',
 'ff': 'Fulah',
 'fi': 'Finnish',
 'fr': 'French',
 'fy': 'Western_Frisian',
 'ga': 'Irish',
 'gd': 'Gaelic_Scottish_Gaelic',
 'gl': 'Galician',
 'gu': 'Gujarati',
 'ha': 'Hausa',
 'he': 'Hebrew',
 'hi': 'Hindi',
 'hr': 'Croatian',
 'ht': 'Haitian_Haitian_Creole',
 'hu': 'Hungarian',
 'hy': 'Armenian',
 'id': 'Indonesian',
 'ig': 'Igbo',
 'ilo': 'Iloko',
 'is': 'Icelandic',
 'it': 'Italian',
 'ja': 'Japanese',
 'jv': 'Javanese',
 'ka': 'Georgian',
 'kk': 'Kazakh',
 'km': 'Central_Khmer',
 'kn': 'Kannada',
 'ko': 'Korean',
 'lb': 'Luxembourgish_Letzeburgesch',
 'lg': 'Ganda',
 'ln':

In [ ]:
# Sample texts
article_en = 'The Secretary-General of the United Nations says there is no military solution in Syria.'
 
notre_dame_str = "As at most other universities, Notre Dame's students run a number of news media outlets. The nine student - run outlets include three newspapers, both a radio and television station, and several magazines and journals. Begun as a one - page journal in September 1876, the Scholastic magazine is issued twice monthly and claims to be the oldest continuous collegiate publication in the United States. The other magazine, The Juggler, is released twice a year and focuses on student literature and artwork. The Dome yearbook is published annually. The newspapers have varying publication interests, with The Observer published daily and mainly reporting university and other news, and staffed by students from both Notre Dame and Saint Mary's College. Unlike Scholastic and The Dome, The Observer is an independent publication and does not have a faculty advisor or any editorial oversight from the University. In 1987, when some students believed that The Observer began to show a conservative bias, a liberal newspaper, Common Sense was published. Likewise, in 2003, when other students believed that the paper showed a liberal bias, the conservative paper Irish Rover went into production. Neither paper is published as often as The Observer; however, all three are distributed to all students. Finally, in Spring 2008 an undergraduate journal for political science research, Beyond Politics, made its debut."
 
bacteria_str = "Bacteria are a type of biological cell. They constitute a large domain of prokaryotic microorganisms. Typically a few micrometres in length, bacteria have a number of shapes, ranging from spheres to rods and spirals. Bacteria were among the first life forms to appear on Earth, and are present in most of its habitats."
 
bio_str = "Biology is the science that studies life. What exactly is life? This may sound like a silly question with an obvious answer, but it is not easy to define life. For example, a branch of biology called virology studies viruses, which exhibit some of the characteristics of living entities but lack others. It turns out that although viruses can attack living organisms, cause diseases, and even reproduce, they do not meet the criteria that biologists use to define life."
 

In [ ]:
### Tokenization
t2t.Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).tokenize()

[['▁Let', "'", 's', '▁go', '▁hik', 'ing', '▁tom', 'orrow'],
 ['▁안녕', '하세요', '.'],
 ['▁', '돼', '지', '꿈', '을', '▁꾸', '세요', '~~']]

In [ ]:
# Embeddings
t2t.Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).vectorize()

In [ ]:
### TF-IDF
t2t.Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).tfidf()

[{"'": 0.3535533905932738,
  'ing': 0.3535533905932738,
  'orrow': 0.3535533905932738,
  's': 0.3535533905932738,
  '▁Let': 0.3535533905932738,
  '▁go': 0.3535533905932738,
  '▁hik': 0.3535533905932738,
  '▁tom': 0.3535533905932738},
 {'.': 0.5773502691896258,
  '▁안녕': 0.5773502691896258,
  '하세요': 0.5773502691896258},
 {'~~': 0.3535533905932738,
  '▁': 0.3535533905932738,
  '▁꾸': 0.3535533905932738,
  '꿈': 0.3535533905932738,
  '돼': 0.3535533905932738,
  '세요': 0.3535533905932738,
  '을': 0.3535533905932738,
  '지': 0.3535533905932738}]

In [ ]:
### BM25
t2t.Handler([
         "Let's go hiking tomorrow", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~"
         ]).bm25()

In [ ]:
### Index
index = t2t.Handler([
         "Let's go hiking tomorrow, let's go!", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~",
         ]).index(ids=[100, 101, 102])

index.search(["돼지", "안녕", "let's go"], k=1) # Matching L2 distances and corresponding ids

In [ ]:
# Add documents incrementing on ids if none specified
index.add(["Hello, World! 你好,世界!"])

# Remove by ids
index.remove([101])

# Retrieve k results per query sorted by distance
index.search(["你好, World"], k=3)

In [ ]:
### Search
t2t.Handler([
         "Let's go hiking tomorrow, let's go!", 
         "안녕하세요.", 
         "돼지꿈을 꾸세요~~",
         ]).search(queries=["go", "안녕"]).toarray()

array([[0.4472136 , 0.        , 0.        ],
       [0.        , 0.57735027, 0.        ]])

In [ ]:
#### Multiple queries on a single index
bm25_index = t2t.Handler([
                       article_en, 
                       notre_dame_str, 
                       bacteria_str, 
                       bio_str
                       ]).bm25(output="matrix")

search_results_bm25 = t2t.Handler().search(
    queries=["wonderful life", "university students"], 
    vector_class=t2t.Bm25er,
    index=bm25_index)

search_results_bm25_2 = t2t.Handler().search(
    queries=["Earth creatures are cool", "United Nations"], 
    vector_class=t2t.Bm25er,
    index=bm25_index)

In [ ]:
#### Using TF-DF embeddings index
tfidf_index = t2t.Handler([
                       article_en, 
                       notre_dame_str, 
                       bacteria_str, 
                       bio_str
                       ]).tfidf(output="matrix")

search_results_tf = t2t.Handler().search(
    queries=["wonderful life", "university students"], 
    vector_class=t2t.Tfidfer,
    index=tfidf_index)

In [ ]:
#### Using neural embeddings index
embedding_index = t2t.Handler([
                       article_en, 
                       notre_dame_str, 
                       bacteria_str, 
                       bio_str
                       ]).vectorize()

search_results_em = t2t.Handler().search(
    queries=["wonderful life", "university students"],
    vector_class=t2t.Vectorizer,
    index=embedding_index)

In [ ]:
#### Blending neural embeddings and tf-idf
import numpy as np

np.mean( 
    np.array([
              search_results_bm25,
              search_results_tf,
              search_results_em,
              ]), axis=0)

# averaged scores matrix
#matrix([[ 0.00486117, -0.01890325,  0.53769584,  0.82506883],
#        [ 0.0435048 ,  1.68977281,  0.01238902,  0.01266839]])

array([[ 0.00729176, -0.02835486,  0.0024925 ,  0.08656652],
       [ 0.06525719,  0.13328168,  0.0185835 ,  0.01900256]])

In [ ]:
### Levenshtein Sub-word Edit Distance
t2t.Handler([
         "Hello, World! [SEP] Hello, what?", 
         "안녕하세요. [SEP] 돼지꿈을 꾸세요~~"
        ]).measure(metric="levenshtein_distance")

[2, 8]

In [ ]:
### Translation
# Default translator model
t2t.Handler([article_en, notre_dame_str, bacteria_str, bio_str], src_lang='en').translate(tgt_lang='zh')

In [ ]:
# Smaller model to save time and memory for development
t2t.Transformer.PRETRAINED_TRANSLATOR = "facebook/m2m100_418M"
t2t.Handler(["I would like to go hiking tomorrow."], 
        src_lang="en"
        ).translate(tgt_lang='zh')


In [ ]:
# Smaller model to save time and memory for development
# Note language code difference
t2t.Transformer.PRETRAINED_TRANSLATOR = "facebook/mbart-large-50-many-to-many-mmt"
t2t.Transformer.LANGUAGES = {
  'af_ZA': 'Afrikaans',
  'ar_AR': 'Arabic',
  'az_AZ': 'Azerbaijani',
  'bn_IN': 'Bengali',
  'cs_CZ': 'Czech',
  'de_DE': 'German',
  'en_XX': 'English',
  'es_XX': 'Spanish',
  'et_EE': 'Estonian',
  'fa_IR': 'Persian',
  'fi_FI': 'Finnish',
  'fr_XX': 'French',
  'gl_ES': 'Galician',
  'gu_IN': 'Gujarati',
  'he_IL': 'Hebrew',
  'hi_IN': 'Hindi',
  'hr_HR': 'Croatian',
  'id_ID': 'Indonesian',
  'it_IT': 'Italian',
  'ja_XX': 'Japanese',
  'ka_GE': 'Georgian',
  'kk_KZ': 'Kazakh',
  'km_KH': 'Khmer',
  'ko_KR': 'Korean',
  'lt_LT': 'Lithuanian',
  'lv_LV': 'Latvian',
  'mk_MK': 'Macedonian',
  'ml_IN': 'Malayalam',
  'mn_MN': 'Mongolian',
  'mr_IN': 'Marathi',
  'my_MM': 'Burmese',
  'ne_NP': 'Nepali',
  'nl_XX': 'Dutch',
  'pl_PL': 'Polish',
  'ps_AF': 'Pashto',
  'pt_XX': 'Portuguese',
  'ro_RO': 'Romanian',
  'ru_RU': 'Russian',
  'si_LK': 'Sinhala',
  'sl_SI': 'Slovene',
  'sv_SE': 'Swedish',
  'sw_KE': 'Swahili',
  'ta_IN': 'Tamil',
  'te_IN': 'Telugu',
  'th_TH': 'Thai',
  'tl_XX': 'Tagalog',
  'tr_TR': 'Turkish',
  'uk_UA': 'Ukrainian',
  'ur_PK': 'Urdu',
  'vi_VN': 'Vietnamese',
  'xh_ZA': 'Xhosa',
  'zh_CN': 'Chinese'
}
t2t.Handler(["I would like to go hiking tomorrow."], 
        src_lang="en_XX"
        ).translate(tgt_lang='zh_CN')


In [ ]:
### Question Answering. Question must follow context with ` [SEP] ` in between.
t2t.Handler([
         "Hello, this is Text2Text! [SEP] What is this?", 
         "It works very well. It's awesome! [SEP] How is it?"
         ]).answer()

In [ ]:
t2t.Handler(["很喜欢陈慧琳唱歌。[SEP] 喜欢做什么?"], 
        src_lang="zh",
        ).answer()

In [ ]:
### Question Generation
t2t.Handler([
            bio_str,
            bio_str,
            bio_str,
            bio_str,
            bio_str,
            "I will go to school today to take my math exam.",
            "I will go to school today to take my math exam.",
            "Tomorrow is my cousin's birthday. He will turn 24 years old.",
            notre_dame_str,
            bacteria_str,
            bacteria_str,
            bacteria_str,
            "I will go to school today to take my math exam. [SEP] school",
            "I will go to school today to take my math exam. [SEP] exam",
            "I will go to school today to take my math exam. [SEP] math",
          ], src_lang='en').question()

In [ ]:
t2t.Handler(["很喜欢陈慧琳唱歌。"], src_lang='zh').question()

In [ ]:
### Summarization
t2t.Handler([notre_dame_str, bacteria_str, bio_str], src_lang='en').summarize()

In [ ]:
### Variation
# Useful for augmenting training data
t2t.Handler([bacteria_str], src_lang='en').variate()

In [ ]:
### Training / Fine-tuning
# Finetune cross-lingual model on your data
result = t2t.Handler(["Hello, World! [TGT] 你好,世界!"], 
            src_lang="en",
            tgt_lang="zh",
            num_epochs=10, 
            save_directory="model_dir"
            ).fit()

# load and use model from saved directory
t2t.Transformer.PRETRAINED_TRANSLATOR = "model_dir"
t2t.Handler("Hello, World!").translate(tgt_lang="zh")